spring:
  datasource:
    url: jdbc:mysql://localhost:3306/crypto_platform?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 19880806

# 开发环境日志级别
logging:
  level:
    com.crypto.platform: debug
    com.baomidou.mybatisplus: debug
    org.springframework.security: debug

